# To see all available options, please visit the docs:
# https://docs.digpangolin.com/

gerbil:
    start_port: 51820
    base_endpoint: "{{.DashboardDomain}}"

app:
    dashboard_url: "https://{{.DashboardDomain}}"
    log_level: "info"
    telemetry:
        anonymous_usage: true

domains:
    domain1:
        base_domain: "{{.BaseDomain}}"
        cert_resolver: "letsencrypt"

server:
    secret: "{{.Secret}}"
    cors:
        origins: ["https://{{.DashboardDomain}}"]
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        allowed_headers: ["X-CSRF-Token", "Content-Type"]
        credentials: false
    {{if .EnableGeoblocking}}maxmind_db_path: "./config/GeoLite2-Country.mmdb"{{end}}
{{if .EnableEmail}}
email:
    smtp_host: "{{.EmailSMTPHost}}"
    smtp_port: {{.EmailSMTPPort}}
    smtp_user: "{{.EmailSMTPUser}}"
    smtp_pass: "{{.EmailSMTPPass}}"
    no_reply: "{{.EmailNoReply}}"
{{end}}
flags:
    require_email_verification: {{.EnableEmail}}
    disable_signup_without_invite: true
    disable_user_create_org: false
    allow_raw_resources: true